### ISSUE TITLE
Weird route

### ISSUE THREAD

**Issue by jbelien** [anyways-open/cycling-frontend#30]
![image](https://user-images.githubusercontent.com/1150563/83616183-cf946b80-a587-11ea-93b9-352a0006aefa.png)
https://routeplanner.bike.brussels/#14.20/50.8724/4.3544?sb=true&o=4.3524161,50.8725291&d=4.3718563,50.8699161&p=profile1

Not exactly sure why it jumps on `PP` + `SZ` instead of staying on `B`.

**Comment by xivk** [comment]
This part is oneway, also for cyclists:

https://www.openstreetmap.org/way/526248199

**Comment by xivk** [comment]
Aaand it's pretty clear this is not the case on the ground:

https://www.mapillary.com/app/?pKey=8qYaGeUjitWp8vGFzA-khg&focus=photo

**Comment by jbelien** [comment]
Yep ! I was looking at it too !
Thanks for the catch and the fix ! 👌

**Comment by xivk** [comment]
Should be fixed tomorrow after data update:

https://www.openstreetmap.org/changeset/86125165

To be closed when confirmed! Thanks @jbelien :heart_eyes:

**Comment by jbelien** [comment]
I also fixed `oneway` attributes for
- https://www.openstreetmap.org/way/559845586
- https://www.openstreetmap.org/way/812447827

**Comment by jbelien** [comment]
![image](https://user-images.githubusercontent.com/1150563/83844470-5a4fa480-a707-11ea-87c8-43bebc5760de.png)
Route is correct now but it appears in black.

But after I cleaned the local storage, it was back to the original issue (using `PP` + `SZ` instead of `B`)

PS : "Recreational" and "Commute" profiles take the right route.

**Comment by xivk** [comment]
We are testing a new routing profile in one of the three instances. Thanks for spotting this, the routes being black is something broken that we didn't notice yet. cc @pietervdvn

**Comment by xivk** [comment]
Cause of the issue, the change in route profiles changed the output. For example:

```
       "name": "Rue Marie-Christine - Maria-Christinastraat",
        "highway": "tertiary",
        "maxspeed": "30",
        "surface": "asphalt",
        "_relation:brussels:bicycle_network_by_operator": "yes",
        "_relation:commute:bicycle_network_by_operator": "yes",
        "_relation:b2w:bicycle_network_by_operator": "yes",
        "_relation:bicycle_network_is_bicycle_network": "yes",
        "profile": "bicycle.brussels",
        "distance": "580.07404",
        "time": "139.79376"
```

used to be this:
```
        "name": "Rue Marie-Christine - Maria-Christinastraat",
        "cycle_network_colour": "#932F34,#F6A31A",
        "highway": "tertiary",
        "maxspeed": "30",
        "surface": "asphalt",
        "cycle_network": "yes",
        "StadGenk": "yes",
        "Anyways": "yes",
        "BrusselsMobility": "yes",
        "profile": "bicycle.brussels",
        "distance": "580.07404",
        "time": "139.79376"
```

Most likely the 'cycle_network_colour' attribute is needed.

**Comment by xivk** [comment]
Ok the update is done but route still doesn't look very good:

![image](https://user-images.githubusercontent.com/1128068/83878455-1d4dd700-a734-11ea-880b-0e64aa97bef4.png)

**Comment by jbelien** [comment]
Awesome! Thanks :)

--- 

I don't really understand that "decision":
![image](https://user-images.githubusercontent.com/1150563/83881485-09f53880-a741-11ea-96b4-7b485c9b7cee.png)

---

And would it be possible to "prioritize" to stay on route `B` (even if it's a bit longer) ?
![image](https://user-images.githubusercontent.com/1150563/83881701-580a3c00-a741-11ea-83bb-83ee454d6d65.png)

**Comment by xivk** [comment]
Split into:

https://github.com/anyways-open/cycling-routeplanner/issues/33
https://github.com/anyways-open/cycling-routeplanner/issues/34
